name: Benchmark

on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

  merge_group:

  workflow_dispatch:

jobs:
  benchmark:
    runs-on: macos-14
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install Pnpm
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Run Benchmark
        run: pnpm run benchmark
